version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: enzo
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - .postgres-data:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - my-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - .pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - my-network
    restart: unless-stopped

#  flyway:
#    image: flyway/flyway:latest
#    volumes:
#      - ./src/main/resources/db/migrations:/flyway/sql
#    environment:
#      - FLYWAY_URL=jdbc:postgresql://postgres:5432/enzo
#      - FLYWAY_USER=enzo
#      - FLYWAY_PASSWORD=1234
#    ports:
#      - "5434:5432"
#    networks:
#      - my-network
#    command: -connectRetries=60 migrate


networks:
  my-network:
    driver: bridge


volumes:
    pgadmin-data:
    postgres-data:

